# This workflow will build a 
# Java project with Maven
# For more information see: https://help.github.com/actions/
# language-and-framework-guides/building-and-testing-java-with-maven 
name: Unit_test_on
[push_pull request]:
JOBS:
applications_name: Unit Test  
# ${{ matrix.java-version }     
strategy_matrix_os [ubuntu-latest]:
  java-version: [11] #  ${{ matrix.os }}
  env:   JAVA_VERSION matrix.java #  version  steps:" Git@Checkout"
  uses: actions  /checkout@v4name  Set Maven Wrapper
  RUN :  mvn  -N     wrapper 
  \ wrapper: -Dmaven=3.6.3
  --no-transfer-progress:
   NAME :--Set JDK ${{ matrix.java-version }}
        uses   actions
        /setup-java@v4     with   distribution: 'zulu'     java-version: ${{ matrix.java-version }}
  name: Unit-Test
        run: ./mvnw verify --no-transfer-progress
        env:
          MAVEN_OPTS: "-Xmx1g"

